---
title: "conclusion.qmd"
---

Based on the results of the analysis, it is highly probable that the power plant on Dauphin Island, Alabama will need to operate at reduced capacity due to the temperature of the water. Data from recent water temperatures and implications that overall temperatures will continue to rise in the coming years lead to the assumption that the power plant needs to prepare for operating at reduced capacity. The plant should take the necessary precautions to still give out an optimal energy output while not operating at full capacity. Until further data suggests that average temperatures will decrease in the coming years, the summer months are a time that the power plant will likely need to operate at reduced capacity.

Recommendations on how to counteract these high water temperatures in the summer months include harvesting water from deeper in the gulf, and upgrading the heat exchangers. Harvesting cooler water from the gulf is not the preferred adjustment to make, due to the fact that the depths around Dauphin Island is less than 30 feet. According to @NOAAWaterTemp, significant changes in water temperature isn't observed until a depth of 200 feet. Knowing this, the availability or access to cooler water is very limited. Upgrading the heat exchangers inside the power plant is much more plausible. @heatexc labels heat exchangers as a piece of equipment that transfers heat from one medium to another. Heat exchangers are needed to provide heating or cooling to help enable a process. Power plants need the water to be cooler, so upgrading pieces like the heat echangers and things like distribution nozzles will help cool the water substantially, allowing the plant to operate at a more efficient rate.
