---
title: "Draft: Executive Summary"
---

Power plants often rely on water to help produce the energy needed to sustain the infrastructure of the economy. When the water temperature rises, it leads to an output reduction in electrical output due to the lost temperature differential between the plant's system and the water temperature. The power plants near Dauphin Island, Alabama operate at a normal rate while the temperature of the water that feeds into it is below 85 degrees Fahrenheit. When that threshold is surpassed, the plant must operate at a reduced capacity to avoid internal problems in the plant, such as **grid failures** and damage to **aquatic ecosystems**.

Water temperature measurements were taken from @NOAA over the span of one year (March 9th, 2022 - March 8th, 2023) in one hour intervals using a sensor that reported the surface temperature of the water in degrees Fahrenheit. Energy data was taken from @EIA, looking at the Southeast region of the country (including Alabama), and the monthly energy demand over the same time span.

The results of the water temperature data showed that the summer months experience numerous occasions where the water temperature reaches 85 degrees Fahrenheit or higher. There were a total of 1767 measurements (or hours) of the water exceeding the 85 degree threshold over the span of a year. Due to recent data about global warming from @climate2025, there is no way to conclude that the surface temperature of the water will be cooler in the summer months due to increasing global temperatures.

Evaluating the relationship between water temperature near Dauphin Island Alabama and the electrical demand in the southeast sector of the united states, it gave a p-value less than 0.05 (4.559764e-28), concluding that this relationship is significant and the high water temperatures play a considerable factor in the electrical demand, and should not be overlooked.

Recommendations for the plant to prepare for these occurrences, especially during the summer months, include attempting to harvest **cooler water** from deeper in the gulf, and upgrading the cooling systems in the plant as to not delay the process when water temperatures go above 85 degrees.  
