# Introduction

Electrical demand changes over the course of a year. The AC unit in your house requires larger amounts of power in the summer months to keep your house cool. In addition, the heating system requires more power in the colder winter months. Power plants react to certain temperatures a little differently. The capacity that a power plant works at is dependent on natural circumstances. Things like extreme temperatures and storms have a massive influence on the energy demand that these power plants require. Obviously, power plants require a lot more energy to do their job compared to the heating and cooling systems in your house, but what makes power plants unique is that they operate more efficiently in the winter months. The reasoning behind this is because a majority of power plants are thermal power plants, which @whatis2025 defines as facilities that generate electricity by harnessing the heat energy from various sources. When the weather is cold, the power plant can operate more efficiently because the difference between the outside temperature and the operating temperature of the plant is greater, and opposite is true; the plant is less efficient in the summer months due to a smaller temperature differential.

The same way that the capacity of a plant is reliant on temperature, the temperature of the water will also have an impact on the total energy load that a power plant can handle. This claim is specifically true for power plants that rely on near by bodies of water to generate power. This report assesses the threat of increasing Gulf temperatures to the ability to safely and economically operate the plant. As part of this risk assessment, the report also considers the economic consequences of reduced generation capacity in order to assess whether equipment upgrades or plant modifications to counteract temperature increases should be considered when planning future operations.

